name: Train UNet Model
description: Trains UNet model using dataset directory from CDN data loader brick
inputs:
  
outputs:
implementation:
  container:
    image: nikhilv215/nesy-factory:v22
    command:
      - sh
      - -c
      - |
        set -e
        exec "$0" "$@"
      - python3
      - -u
      - -c
      - |
        
    args:

